name: Build Flutter Android APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Generate .env from GitHub Secrets
        run: |
          echo "CAT_API_KEY=${{ secrets.CAT_API_KEY }}" >> .env
          echo "DOG_API_KEY=${{ secrets.DOG_API_KEY }}" >> .env    

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test

      - name: Build APK (Production)
        run: flutter build apk --release --flavor production -t lib/main_production.dart
        env:
          CI: true
          FLUTTER_SUPPRESS_ANALYTICS: true

      - name: Upload Production APK
        uses: actions/upload-artifact@v4
        with:
          name: app-production-release-apk
          path: build/app/outputs/flutter-apk/app-production-release.apk

